// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATXtRV5L-c0Xcki1-LXn5ke1urwL3d_i8',
    appId: '1:752702760997:web:4604cf54dd7838b9cd37cc',
    messagingSenderId: '752702760997',
    projectId: 'mencobamodul3',
    authDomain: 'mencobamodul3.firebaseapp.com',
    storageBucket: 'mencobamodul3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6dYzjRWbhEZ_g3w7_3Sy_6mcWcJYNOUc',
    appId: '1:752702760997:android:44de547efd4821b5cd37cc',
    messagingSenderId: '752702760997',
    projectId: 'mencobamodul3',
    storageBucket: 'mencobamodul3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJXd7ut5zEfNkP3rSfILS8TQorCHYWJaY',
    appId: '1:752702760997:ios:bbc66b94df6f8953cd37cc',
    messagingSenderId: '752702760997',
    projectId: 'mencobamodul3',
    storageBucket: 'mencobamodul3.appspot.com',
    iosBundleId: 'com.example.mencobamodul3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJXd7ut5zEfNkP3rSfILS8TQorCHYWJaY',
    appId: '1:752702760997:ios:bbc66b94df6f8953cd37cc',
    messagingSenderId: '752702760997',
    projectId: 'mencobamodul3',
    storageBucket: 'mencobamodul3.appspot.com',
    iosBundleId: 'com.example.mencobamodul3',
  );

}